[32m[I 170324 11:48:53 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py modified; restarting server
[32m[I 170324 11:50:57 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[31m[E 170324 12:13:24 web:1548](B[m Uncaught exception POST /rsync/add (127.0.0.1)
    HttpRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/rsync/add', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8000', 'Content-Length': '176', 'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8000/rsync/add?patharea=&desc=&project=', 'Cookie': 'PHPSESSID=bh2r0tvg47dhk23kqmmgmj14s5; _xsrf=2|a90a53ec|519d406933e3f00c5eb90ce88ae84f34|1489735875; __TORNADOSSID=91A86EFDC8C468631EF1F6214AEA6160F5895727|EtdHjDO1', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py", line 32, in post
        insert = rsyncModel.addRsync(self, params)
    TypeError: addRsync() takes exactly 2 arguments (3 given)
[32m[I 170324 12:13:58 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py modified; restarting server
[32m[I 170324 12:14:56 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[31m[E 170324 12:14:59 web:1548](B[m Uncaught exception POST /rsync/add (127.0.0.1)
    HttpRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/rsync/add', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8000', 'Content-Length': '176', 'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8000/rsync/add?patharea=&desc=&project=', 'Cookie': 'PHPSESSID=bh2r0tvg47dhk23kqmmgmj14s5; _xsrf=2|a90a53ec|519d406933e3f00c5eb90ce88ae84f34|1489735875; __TORNADOSSID=1C7EC180FBA30DE3531921410ED60E689EBE1464|EtdHjDO1', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py", line 32, in post
        insert = rsyncModel.addRsync( params)
      File "/data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py", line 47, in addRsync
        Rsync.session.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
        self._prepare_impl()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
        self.session.flush()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
        self._flush(objects)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
        transaction.rollback(_capture_exception=True)
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
        flush_context.execute()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
        rec.execute(self)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
        uow
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
        mapper, table, insert)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
        execute(statement, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
        exc_info
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
        cursor.execute(statement, parameters)
      File "/Library/Python/2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
        self.errorhandler(self, exc, value)
      File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    OperationalError: (_mysql_exceptions.OperationalError) (1048, "Column 'userip' cannot be null") [SQL: u'INSERT INTO deploy_log (uid, status, username, description, project, files, userip, created, feedback, log_from_server, pid, email) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('100', 0, 'Alex kong', u'1000', u'vogueshows', u'class/controller/mobile/apply.class.php\nclass/model/service/comm.class.php', None, None, None, None, u'8', 'konglingjian@gmail.com')]
[32m[I 170324 12:15:49 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:16:10 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py modified; restarting server
[31m[E 170324 12:16:11 web:1548](B[m Uncaught exception POST /rsync/add (127.0.0.1)
    HttpRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/rsync/add', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8000', 'Content-Length': '176', 'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8000/rsync/add?patharea=&desc=&project=', 'Cookie': 'PHPSESSID=bh2r0tvg47dhk23kqmmgmj14s5; _xsrf=2|a90a53ec|519d406933e3f00c5eb90ce88ae84f34|1489735875; __TORNADOSSID=2F56EA24CEB7E92C43BECEDF2BD751F5F9E25483|EtdHjDO1', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py", line 33, in post
        insert = rsyncModel.addRsync( params)
      File "/data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py", line 47, in addRsync
        Rsync.session.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
        self._prepare_impl()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
        self.session.flush()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
        self._flush(objects)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
        transaction.rollback(_capture_exception=True)
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
        flush_context.execute()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
        rec.execute(self)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
        uow
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
        mapper, table, insert)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
        execute(statement, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
        exc_info
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
        cursor.execute(statement, parameters)
      File "/Library/Python/2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
        self.errorhandler(self, exc, value)
      File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    OperationalError: (_mysql_exceptions.OperationalError) (1048, "Column 'created' cannot be null") [SQL: u'INSERT INTO deploy_log (uid, status, username, description, project, files, userip, created, feedback, log_from_server, pid, email) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('100', 0, 'Alex kong', u'1000', u'vogueshows', u'class/controller/mobile/apply.class.php\nclass/model/service/comm.class.php', '127.0.0.1', None, None, None, u'8', 'konglingjian@gmail.com')]
[32m[I 170324 12:16:35 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:16:39 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:17:18 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:17:39 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:19:00 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[31m[E 170324 12:19:36 web:1548](B[m Uncaught exception POST /rsync/add (127.0.0.1)
    HttpRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/rsync/add', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8000', 'Content-Length': '176', 'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8000/rsync/add?patharea=&desc=&project=', 'Cookie': 'PHPSESSID=bh2r0tvg47dhk23kqmmgmj14s5; _xsrf=2|a90a53ec|519d406933e3f00c5eb90ce88ae84f34|1489735875; __TORNADOSSID=78621A9E7B734ACE483ECC6C3911C30257B155A6|EtdHjDO1', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py", line 33, in post
        insert = rsyncModel.addRsync( params)
      File "/data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py", line 49, in addRsync
        Rsync.session.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
        self._prepare_impl()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
        self.session.flush()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
        self._flush(objects)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
        transaction.rollback(_capture_exception=True)
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
        flush_context.execute()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
        rec.execute(self)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
        uow
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
        mapper, table, insert)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
        execute(statement, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
        exc_info
      File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
        context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
        cursor.execute(statement, parameters)
      File "/Library/Python/2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
        self.errorhandler(self, exc, value)
      File "/Library/Python/2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
        raise errorclass, errorvalue
    OperationalError: (_mysql_exceptions.OperationalError) (1048, "Column 'feedback' cannot be null") [SQL: u'INSERT INTO deploy_log (uid, status, username, description, project, files, userip, created, feedback, log_from_server, pid, email) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('100', 0, 'Alex kong', u'1000', u'vogueshows', u'class/controller/mobile/apply.class.php\nclass/model/service/comm.class.php', '127.0.0.1', 1490329176.683785, None, None, u'8', 'konglingjian@gmail.com')]
[31m[E 170324 12:19:52 web:1548](B[m Uncaught exception POST /rsync/add (127.0.0.1)
    HttpRequest(protocol='http', host='127.0.0.1:8000', method='POST', uri='/rsync/add', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:8000', 'Content-Length': '176', 'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:8000/rsync/add?patharea=&desc=&project=', 'Cookie': 'PHPSESSID=bh2r0tvg47dhk23kqmmgmj14s5; _xsrf=2|a90a53ec|519d406933e3f00c5eb90ce88ae84f34|1489735875; __TORNADOSSID=5B269E1E4FC87A65B4A51C194B41769806AB2CD0|EtdHjDO1', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py", line 25, in post
        projectInfo = projectModel.getProjectInfo(pid)
      File "/data/www/python/www.torngas.com/demo/helloworld/models/project_models.py", line 49, in getProjectInfo
        return Project.Q.filter(Project.id == id).limit(1).all()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2638, in all
        return list(self)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/Library/Python/2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.OperationalError) (1048, "Column 'feedback' cannot be null") [SQL: u'INSERT INTO deploy_log (uid, status, username, description, project, files, userip, created, feedback, log_from_server, pid, email) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: ('100', 0, 'Alex kong', u'1000', u'vogueshows', u'class/controller/mobile/apply.class.php\nclass/model/service/comm.class.php', '127.0.0.1', 1490329176.683785, None, None, u'8', 'konglingjian@gmail.com')]
[32m[I 170324 12:20:19 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/models/rsync_models.py modified; restarting server
[32m[I 170324 12:24:23 autoreload:204](B[m /data/www/python/www.torngas.com/demo/helloworld/handlers/rsync_handler.py modified; restarting server
